module.exports = {
    head1: {
        color:"#000",
        fontSize:30,
        minWidth:120,
        textAlign:"center",
    },
    head2: {
        color:"#000",
        fontSize:17,
        minWidth:120,
        textAlign:"center",
    },
    formgroup:{
        display:"flex", 
        flexDirection:"column",
        width:"100%",
        marginVertical:10,
        paddingHorizonatl:10,
      },
      label:{
        fontSize:17,
        color:"#4E565E",
        borderBlockColor:"gray",
      },
      input:{
        fontSize:17,
        color:"#000",
        borderRadius:12,
        padding:10,
        backgroundColor:"#fff"
      },
      input1:{
        fontSize:17,
        color:"#000",
        borderRadius:12, 
        padding:10,
        backgroundColor:"#fff"
      },
      link:{
        fontSize:15,
        color:"red",
      },
      link2:{
        fontSize:15,
        color:"gray",
        textAlign:"center",
      },
      formgroup1:{
        display:"flex", 
        flexDirection:"column",
        width:"100%",
        marginVertical:10,
        paddingHorizonatl:10,
      },
      input2:{
        fontSize:17,
        color:"#000",
        borderRadius:12, 
        padding:10,
        backgroundColor:"white",
        paddingHorizonatl:10,
        paddingVertical:10,
        height:100,
        textAlignVertical:"top"
      },
      errormessage:{
        color:'white',
        backgroundColor:'#F50057',
        fontSize:15,
        textAlign:'center',
        padding:5,
        borderRadius:10,
      },
      bwmessage:{
        color:'white',
        backgroundColor:'black',
        fontSize:15,
        textAlign:'center',
        padding:5,
        borderRadius:10,
      }
    
    
}